{"name": "Ввод хорошего ключа должен активировать систему", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Session timed out or not found\n\n", "trace": "  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/step_license.py\", line 34, in step_impl\n    context.browser.get(appAddress(context) + path)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 320, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Допустим открыли мы страницу платформы /dashboard/login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Session timed out or not found\n\n", "trace": "  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/step_license.py\", line 34, in step_impl\n    context.browser.get(appAddress(context) + path)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 320, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1510126985025, "stop": 1510126985030}, {"name": "И это оказалась страница ввода лицензии", "status": "skipped", "start": 1510126985030, "stop": 1510126985030}, {"name": "Если мы вводим QEM76LDljaZhkTA0040itSdMqq4J2atX7GZSVNP3EpymLRUOvRQItcjgMI7shzYbMLJGgYMC7eTKTLD0WqebCifYWhuiyx0BkXNGaqnTUw3KMFaFe4nsdiznGxyp1xi0itPZOamO/6zVtjurfSKJS35t7WHF9cACSLkzU4+mvmA= в качестве ключа для пользователя mts", "status": "skipped", "start": 1510126985030, "stop": 1510126985030}, {"name": "То отображается страница входа", "status": "skipped", "start": 1510126985030, "stop": 1510126985030}], "start": 1510126985023, "stop": 1510126985030, "uuid": "926fa5f9-cf9f-4808-97b2-9afc0ba7decb", "historyId": "9279bdaf71fcf6b1466956a642ca3d2b", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "Лицензионные ключи и вход в систему"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}