{"name": "Вход в систему должен работать корректно", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Session timed out or not found\n\n", "trace": "  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/step_license.py\", line 34, in step_impl\n    context.browser.get(appAddress(context) + path)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 320, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Допустим открыли мы страницу платформы /dashboard/login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Session timed out or not found\n\n", "trace": "  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/step_license.py\", line 34, in step_impl\n    context.browser.get(appAddress(context) + path)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 320, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1510126985033, "stop": 1510126985057}, {"name": "И это оказалась страница входа в систему", "status": "skipped", "start": 1510126985058, "stop": 1510126985058}, {"name": "Если мы пытаемся ввойти в систему под логином admin и паролем 123456", "status": "skipped", "start": 1510126985058, "stop": 1510126985058}, {"name": "И обновляем страницу", "status": "skipped", "start": 1510126985058, "stop": 1510126985058}, {"name": "То установлена cookie с именем sessionid", "status": "skipped", "start": 1510126985058, "stop": 1510126985058}, {"name": "И отображается страница по пути /dashboard/cabinet", "status": "skipped", "start": 1510126985058, "stop": 1510126985058}, {"name": "К тому же сохраним значение cookie sessionid в кеш", "status": "skipped", "start": 1510126985058, "stop": 1510126985058}], "start": 1510126985032, "stop": 1510126985058, "uuid": "0feb1d2b-0d1c-4792-aca0-dc3da129c8d6", "historyId": "cd0e377ed03eae1e05b6a7cd8e173f7d", "labels": [{"name": "tag", "value": "wip"}, {"name": "severity", "value": "blocker"}, {"name": "feature", "value": "Лицензионные ключи и вход в систему"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}